#!/bin/bash
if [[ $UID == 0 || $EUID == 0 ]]; then
    echo "Cannot be run as root"
fi

if [[ ! $(which paru 2>/dev/null) ]]; then
    echo "Paru is not installed"
fi

while [ $# -gt 0 ]; do
    case "$1" in
    --packagelist=*)
        argument="${1/--/}"
        declare $argument
        ;;
    *)
        echo "Invalid Argument"
        exit 1
        ;;
    esac
    shift
done

if [[ -n $packagelist ]]; then
    PACKAGES=$packagelist
else
    if [[ -n $DEC_PACKAGELIST ]]; then
        PACKAGES=$DEC_PACKAGELIST
    else
        echo -e "No list of packages specified\nYou can specify one by using --packagelist or by setting DEC_PACKAGELIST"
        exit 1
    fi
fi

paru -Syu
INSTALL=$(paru -Qi $(sort -u "$PACKAGES" | grep -Ev '^#') 2>&1 >/dev/null | grep "^error" | awk '{print $3}' | sed "s/^.//" | sed "s/.$//")
REMOVE=$(diff --new-line-format="" --unchanged-line-format="" <(paru -Qqe | sort -u) <(sort -u "$PACKAGES" | grep -Ev '^#'))
if [[ -n $INSTALL ]]; then
    paru -S $INSTALL
fi
if [[ -n $REMOVE ]]; then
    paru -Rns $REMOVE
    echo $REMOVE
fi
